name: CI/CD 파이프라인

on:
  push:
    branches:
      - main
      - fix-ip-change

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to NCP Container Registry
        run: |
          echo "${{ secrets.NCP_SECRET_KEY }}" | \
          docker login --username ${{ secrets.NCP_ACCESS_KEY }} \
                       --password-stdin vst.kr.ncr.ntruss.com

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: vst.kr.ncr.ntruss.com/vst/my-app:latest
          build-args: |
            API_BASE=http://허용된_API_IP:8080
            CLOVA_BASE=http://허용된_CLOVA_IP:8000
          
  deploy:
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }} 
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            echo "Login to NCP Container Registry..."
            echo "${{ secrets.NCP_SECRET_KEY }}" | \
            docker login --username ${{ secrets.NCP_ACCESS_KEY }} \
                         --password-stdin vst.kr.ncr.ntruss.com

            echo "Pulling latest Docker image..."
            docker pull vst.kr.ncr.ntruss.com/vst/my-app:latest

            echo "Stopping old container..."
            docker stop my-app || true
            docker rm my-app || true

            echo "Starting new container..."
            docker run -d --name my-app -p 3000:3000 vst.kr.ncr.ntruss.com/vst/my-app:latest
